# -*- coding: utf-8 -*-
"""ml-exp_6_multiple_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tIeTVW0PEloSfyP6cwJJKEidAO2uk9V8
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder,LabelEncoder
df=pd.read_csv('hp_data.csv')
df.head()

df.shape

label_encoder = LabelEncoder()
df["place"] = label_encoder.fit_transform(df["place"])
encoder = OneHotEncoder(sparse=False, drop='first')
df["place"] = encoder.fit_transform(df[["place"]])

df.head()

df.drop(columns=['Unnamed: 0','built','sale'],inplace=True)

df.head()

x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:,0],random_state=3)

x_train.shape,x_test.shape

model=LinearRegression()
model.fit(x_train,y_train)

model.intercept_

model.coef_

y_predict=model.predict(x_test)

y_predict

x=df.iloc[:,1:]
y=model.coef_*x+model.intercept_

plt.plot(x,y)

r2_score(y_test,y_predict)

mean_absolute_error(y_test,y_predict)

import math
math.sqrt(mean_squared_error(y_test,y_predict))