# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pw1odk5MdSWgPQjDWj8LftuwVcEjRNPo
"""

import matplotlib as plt
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,confusion_matrix
from sklearn.model_selection import train_test_split
import seaborn as sns

df=pd.read_csv('diabetes.csv')
df

df.shape

X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0],test_size=0.2, random_state=2)
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)
y_predict = knn.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_predict))
print("Precision:",precision_score(y_test, y_predict,average='macro'))
print("Recall:",recall_score(y_test, y_predict,average='macro'))
print("F1 Score:",f1_score(y_test, y_predict,average='macro'))

cm= confusion_matrix(y_test,y_predict)
sns.heatmap(cm,annot=True)